openapi: 3.0.1
info:
  title: Tech Challenge - OpenAPI 3.0
  description: |-
    API desenvolvida pelo Grupo 37 que realiza a análise de dados relacionados à produção, processamento, comercialização, importação e exportação de vinhos.A API permite a integração eficiente de dados vitivinícolas em sistemas e aplicações diversas. 
    
    Alguns links usáveis:
    - [Repositório da API](https://github.com/)
    - [Dados da Vitivinicultura](http://vitibrasil.cnpuv.embrapa.br/index.php?opcao=opt_01)
  termsOfService: http://swagger.io/terms/
  contact: 
    name: 'Contate os desenvolvedores'
    email: Grupo37@exemplo.io
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.pt-br.html
  version: 1.0.11
servers:
  - url: https://664fcb6cec9b4a4a602fda12.mockapi.com/
    description: API mock
tags:
  - name: Produção
    description: Endpoints relacionados à produção de vinhos.
  - name: Processamento - Viníferas
    description: Dados sobre processamento de uvas viníferas.
  - name: Processamento - Americanas e Híbridas
    description: Dados sobre processamento de uvas americanas e híbridas.
  - name: Processamento - Uvas de Mesa
    description: Dados sobre processamento de uvas de mesa.
  - name: Processamento - Sem Classificação
    description: Dados sobre processamento de uvas sem classificação.
  - name: Comercialização
    description: Endpoints relacionados à comercialização de vinhos.
  - name: Importação - Vinhos de Mesa
    description: Dados sobre importação de vinhos de mesa.
  - name: Importação - Espumantes
    description: Dados sobre importação de espumantes.
  - name: Importação - Uvas Frescas
    description: Dados sobre importação de uvas frescas.
  - name: Importação - Uvas Passas
    description: Dados sobre importação de uvas passas.
  - name: Importação - Suco de Uva
    description: Dados sobre importação de suco de uva.
  - name: Exportação - Vinhos de Mesa
    description: Dados sobre exportação de vinhos de mesa.
  - name: Exportação - Espumantes
    description: Dados sobre exportação de espumantes.
  - name: Exportação - Uvas Frescas
    description: Dados sobre exportação de uvas frescas.
  - name: Exportação - Suco de Uva
    description: Dados sobre exportação de suco de uva.
paths:
  /producao:
    get:
      tags:
        - Produção
      summary: Obtém dados de produção de vinhos
      responses:
        '200':
          description: Dados de produção retornados com sucesso
  /processamento/viniferas:
    get:
      tags:
        - Processamento - Viníferas
      summary: Obtém dados de processamento de uvas viníferas
      responses:
        '200':
          description: Dados de processamento de uvas viníferas retornados com sucesso
  /processamento/americanas-hibridas:
    get:
      tags:
        - Processamento - Americanas e Híbridas
      summary: Obtém dados de processamento de uvas americanas e híbridas
      responses:
        '200':
          description: Dados de processamento de uvas americanas e híbridas retornados com sucesso
  /processamento/uvas-mesa:
    get:
      tags:
        - Processamento - Uvas de Mesa
      summary: Obtém dados de processamento de uvas de mesa
      responses:
        '200':
          description: Dados de processamento de uvas de mesa retornados com sucesso
  /processamento/sem-classificacao:
    get:
      tags:
        - Processamento - Sem Classificação
      summary: Obtém dados de processamento de uvas sem classificação
      responses:
        '200':
          description: Dados de processamento de uvas sem classificação retornados com sucesso
  /comercializacao:
    get:
      tags:
        - Comercialização
      summary: Obtém dados de comercialização de vinhos
      responses:
        '200':
          description: Dados de comercialização retornados com sucesso
  /importacao/vinhos-mesa:
    get:
      tags:
        - Importação - Vinhos de Mesa
      summary: Obtém dados de importação de vinhos de mesa
      responses:
        '200':
          description: Dados de importação de vinhos de mesa retornados com sucesso
  /importacao/espumantes:
    get:
      tags:
        - Importação - Espumantes
      summary: Obtém dados de importação de espumantes
      responses:
        '200':
          description: Dados de importação de espumantes retornados com sucesso
  /importacao/uvas-frescas:
    get:
      tags:
        - Importação - Uvas Frescas
      summary: Obtém dados de importação de uvas frescas
      responses:
        '200':
          description: Dados de importação de uvas frescas retornados com sucesso
  /importacao/uvas-passas:
    get:
      tags:
        - Importação - Uvas Passas
      summary: Obtém dados de importação de uvas passas
      responses:
        '200':
          description: Dados de importação de uvas passas retornados com sucesso
  /importacao/suco-uva:
    get:
      tags:
        - Importação - Suco de Uva
      summary: Obtém dados de importação de suco de uva
      responses:
        '200':
          description: Dados de importação de suco de uva retornados com sucesso
  /exportacao/vinhos-mesa:
    get:
      tags:
        - Exportação - Vinhos de Mesa
      summary: Obtém dados de exportação de vinhos de mesa
      responses:
        '200':
          description: Dados de exportação de vinhos de mesa retornados com sucesso
  /exportacao/espumantes:
    get:
      tags:
        - Exportação - Espumantes
      summary: Obtém dados de exportação de espumantes
      responses:
        '200':
          description: Dados de exportação de espumantes retornados com sucesso
  /exportacao/uvas-frescas:
    get:
      tags:
        - Exportação - Uvas Frescas
      summary: Obtém dados de exportação de uvas frescas
      responses:
        '200':
          description: Dados de exportação de uvas frescas retornados com sucesso
  /exportacao/suco-uva:
    get:
      tags:
        - Exportação - Suco de Uva
      summary: Obtém dados de exportação de suco de uva
      responses:
        '200':
          description: Dados de exportação de suco de uva retornados com sucesso

 